# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16bdb33ec0882c2a676b80de711fed58d66ca5972a0cbd0f75e8ea0db6fd61dd485f7386d7fa376630b02ad08ff3f68da306bd5421b75028de239bd24656c793

test:
  secret_key_base: 3c4a4b863b22e3e9b0c927742261a9f7a4c2d625d9050900f8bdee84a29ef00029d773c48523f311948230a03d8eaef881e0e3af5a65ff78d97b66c99a41179f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
